# Generated by Django 5.2.3 on 2025-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='signature',
            field=models.CharField(max_length=100),
        ),
    ]
