# Generated by Django 5.2.3 on 2025-06-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='- Vittorio Ratto', max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
