# Generated by Django 5.2.3 on 2025-07-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_delete_blogpost_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the post was last updated', verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date the question was last updated', verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='Text for the choice', max_length=100, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='personal.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='Number of votes for this choice', verbose_name='Votes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Content of the post', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the post was created', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('blog', 'Blog Post')], default='post', help_text='Type of the post', max_length=10, verbose_name='Post Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(blank=True, help_text='Optional author signature', max_length=100, null=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter the post title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the question was published', verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Enter the question text', max_length=200, verbose_name='Question Text'),
        ),
    ]
