# Generated by Django 5.2.3 on 2025-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Anonymous', help_text='Author signature', max_length=100, verbose_name='Signature'),
        ),
    ]
